language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_scripts:
    - travis_retry composer self-update
    - travis_retry composer install

script:
    - ./vendor/bin/phpunuit --coverage-text
